### PR TITLE
Corrected the installation procedure

### PR DESCRIPTION
**Pull request by LesnyRumcajs**
Now it can be put into a script. Also added suggestion for using parallel jobs in `make`.

### CODE REVIEW

**Comment by LesnyRumcajs** [comment]
@googlebot I signed it!

**Comment by LebedevRI** [comment]
Just to try to avoid tens more PR's, any other obvious-ish typos/issues?

**Comment by LesnyRumcajs** [comment]
@LebedevRI Actually yes, the build directory was outside the benchmark library which I find unusual (and doesn't comply with the installation guide).

**Comment by LebedevRI** [comment]
Ok, lg i guess.

**Pull request merged**
