### PR TITLE
add support for Elbrus 2000 (e2k)

### PR DESCRIPTION
**Pull request by SSE4**

### CODE REVIEW

**Comment by LebedevRI** [comment]
Thanks, waiting for bots.

**Comment by dominichamon** [comment]
thank you!

**Review by akagamy55 — COMMENTED** [review]
Close:(4fd5da1e7ce3437a91f181849575069734767bd8)

**Comment by akagamy55** [comment]
Close:(- add support for Elbrus 2000 (e2k))

**Pull request merged**
