### PR TITLE
Use status messages to not count as errors in ccmake

### PR DESCRIPTION
**Pull request by mattkretz**
Using `ccmake` one gets to acknowledge all those `message("-- ...")` lines after the configure step as errors (you have to press 'e' to continue). This is confusing. Use `message(STATUS "...")` instead.

### CODE REVIEW

**Comment by mattkretz** [comment]
I hope you can count this as not being "original source code", wrt. the CLA. I can get a CLA signed by my  company. But I expect at least 3 months, likely longer delay for this trivial change.

**Comment by dominichamon** [comment]
checking with our CLA experts to see what's possible.

**Comment by mattkretz** [comment]
> checking with our CLA experts to see what's possible.

I guess it's faster/easier if I report an issue with a suggestion how to fix 
it? ;-)

**Comment by dominichamon** [comment]
Resolved in bb15a4e3bf4c5941ee7124d284ed9ef96e9a1c68.

Thanks, @mattkretz!

**Pull request closed without merging**
