### PR TITLE
fix typo in README

### PR DESCRIPTION
**Pull request by tabokie**
Fix an unsuitable for loop in README sample code.

### CODE REVIEW

**Comment by tabokie** [comment]
check again @googlebot

**Comment by LebedevRI** [comment]
I think bot reacts to comments like https://github.com/google/benchmark/pull/846#issuecomment-516135950
I'm not sure about `CONTRIBUTORS`/`AUTHORS` files - when should they be updated.

**Comment by tabokie** [comment]
@googlebot I signed it!

**Comment by LebedevRI** [comment]
LG

**Pull request merged**
