### PR TITLE
[#1487] ensure background color is preserved

### PR DESCRIPTION
**Pull request by imrichardcole**
As raised in issue 1487, the color of the background on Windows was assumed to be black.  This means that when printing results in, for example, green, you ended up with green on black regardless of the original background color.

This update retains the background colors when printing.

This naturally raises another topic of, does the output color want to be determined by the background color when printing?  I.e we would now end up printing green text on a green background if that were the case.  Maybe this can be captured in another request if it's desirable.

### CODE REVIEW

**Comment by imrichardcole** [comment]
image

**Comment by imrichardcole** [comment]
image

**Comment by dmah42** [comment]
clang-format fixes needed but also #1867 probably needed.

**Comment by imrichardcole** [comment]
Sorry, I need to get myself setup locally with clang-tidy so I don't put pressure on these actions prematurely

**Comment by dmah42** [comment]
> Sorry, I need to get myself setup locally with clang-tidy so I don't put pressure on these actions prematurely

i do have it set up locally and i still get it wrong.  it's fine, it's what the actions are there for.

**Review by dmah42 — APPROVED** [review]

**Review by dmah42 — DISMISSED** [review]

**Comment by dmah42** [comment]
```
-                                             FOREGROUND_INTENSITY | 
+                                             FOREGROUND_INTENSITY |
```

i'm struggling to see the difference... is it one more space on the second one?

**Comment by imrichardcole** [comment]
Yes, I'm struggling to get clang-format-lint to be happy.

**Comment by dmah42** [comment]
took a closer look.  on that line above there's an extra space after the |

**Review by dmah42 — APPROVED** [review]

**Comment by dmah42** [comment]
thank you!

**Pull request merged**
