### PR TITLE
Enable Large-file Support

### PR DESCRIPTION
**Pull request by oToToT**
This should fix https://github.com/google/benchmark/issues/1725

### CODE REVIEW

**Comment by dmah42** [comment]
i'm not sure how necessary this is (see my comment on #1725 ) but if we do need it please also add these definitions to the bazel build.

**Review by dmah42 — APPROVED** [review]

**Comment by dmah42** [comment]
i don't know what the pre-commit failure means or why it's an issue that the bazel file has changed in an expected way.  maybe do what it says (`pre-commit run --all-files`).

perhaps some file is being generated based on the BUILD.bazel?

**Comment by oToToT** [comment]
Looks like I accidentally use tabs instead of whitespaces as indent. It should be fixed now.

**Review by dmah42 — APPROVED** [review]

**Comment by dsharlet** [comment]
Is there a way to disable this change? Our project updated to a newer version of googlebenchmark, and this change breaks on some platforms, e.g.: https://github.com/google/XNNPACK/actions/runs/13079108015/job/36498319833

**Comment by dsharlet** [comment]
I share @dmah42 's confusion about why this would be necessary, I doubt the benchmark framework attempts to work with such large files that this matters.

**Comment by dmah42** [comment]
should the flags be conditionally included on 64-bit platforms only?

**Comment by oToToT** [comment]
> should the flags be conditionally included on 64-bit platforms only?

IIUC, LFS is mainly for 32-bit platforms [1], so it has no sense to only include it on 64-bit platforms. (e.g. `ftell` should already be returning 64-bit values on 64-bit platforms)

It seems like XNNPACK is using r23b ndk [2]. Is it possible to raise it to r24? From my random searching, update the target to r24 should make LFS available. (I haven't tested it locally, so please correct me if I'm wrong.)

cc @vapier for vis

[1] https://en.wikipedia.org/wiki/Large-file_support
[2] https://github.com/google/XNNPACK/blob/c467d1a1b79db7c2686536720989cf524308eb4e/.github/workflows/build.yml#L277-L282

**Comment by dsharlet** [comment]
Even with the latest NDK available, this same problem exists: https://github.com/google/XNNPACK/actions/runs/13122183940/job/36610509007?pr=7770

I really think we just need a way to disable this, and failing that, consider reverting it (I don't understand the motivation for this change).

**Comment by oToToT** [comment]
> Even with the latest NDK available, this same problem exists: https://github.com/google/XNNPACK/actions/runs/13122183940/job/36610509007?pr=7770
> 
> I really think we just need a way to disable this, and failing that, consider reverting it (I don't understand the motivation for this change).

I think it works now after you have correctly updated both NDK version and compile flags.

**Comment by dmah42** [comment]
my understanding of the motivation is that on some platforms (OSes) the inode can be 64-bit, meaning that without this we can get hard-to-find errors on I/O.  if there's a way to limit this change to those platforms, then let's do that.  otherwise, i'm happy to revert it until we see those errors in the wild.

PRs welcome for either.

**Comment by oToToT** [comment]
Do we still need to revert it even XNNPACK has already solved the issue themselves?

https://github.com/google/XNNPACK/commit/411f9dea4e79c121f8adb2fa8eecabd7fd616555

**Comment by dmah42** [comment]
if they were the only folks with an issue then no i don't think we do.

**Pull request merged**
