### PR TITLE
add PERF_FORMAT_TOTAL_TIME_{ENABLED,RUNNING} to support multiplexing

### LINKED ISSUE #1813: [BUG] Perf counters not multiplexed
**Describe the bug**

We do not seem to fully support multiplexing in benchmark perf_counters, which can result in undercounting by a factor of 2..3.

There is an attempt to have multiple 'leaders' and we do specify `PERF_FORMAT_GROUP`, but not `PERF_FORMAT_TOTAL_TIME_ENABLED` nor `PERF_FORMAT_TOTAL_TIME_RUNNING`. The latter two are required to extrapolate the counter values according to how long they are running.

**System**
  - OS: Linux
  - Compiler and version: clang near trunk

**To reproduce**
Request many (>6) counters.

**Expected behavior**
Values are scaled according to the relative time during which the counter was enabled/bound to HW.

**Additional context**

From the [manual](https://man7.org/linux/man-pages/man2/perf_event_open.2.html):

If PERF_FORMAT_GROUP was specified to allow reading all events
          in a group at once:

              struct read_format {
                  u64 nr;            /* The number of events */
                  u64 time_enabled;  /* if PERF_FORMAT_TOTAL_TIME_ENABLED */
                  u64 time_running;  /* if PERF_FORMAT_TOTAL_TIME_RUNNING */
                  struct {
                      u64 value;     /* The value of the event */

### PR DESCRIPTION
**Pull request by dmah42**
Fixes #1813

### CODE REVIEW

**Comment by jan-wassenberg** [comment]
Nice, thanks for adding :) I think this does not fully fix the issue. Adding the flags changes the in-memory layout of the counters. It remains to add those to the struct, replacing the 'padding' field, and then to extrapolate the counters based on the fraction of enabled/running.

**Comment by dmah42** [comment]
do you have a pointer? i have no idea how this is meant to work.

**Comment by jan-wassenberg** [comment]
Check out cl/638153709 :)

**Comment by jan-wassenberg** [comment]
SG. In the meantime, probably best to revert this commit.

**Pull request merged**
