### PR TITLE
Add -Wsign-conversion to cmake and BUILD files

### PR DESCRIPTION
**Pull request by oontvoo**

### CODE REVIEW

**Comment by LebedevRI** [comment]
Isn't it `-Wsign-conversion`?

**Comment by dmah42** [comment]
> Isn't it `-Wsign-conversion`?

gcc: error: unrecognized command-line option '-Wsign_conversion'; did you mean '-Wsign-conversion'? :)

**Comment by oontvoo** [comment]
oops - my bad!

**Comment by oontvoo** [comment]
Ok - some tests are failing due to the new warnings (yay!)
Updating them now - pls hold off reviewing

**Comment by LebedevRI** [comment]
It seems this got swapped out.
Let's reopen this when needed.

**Pull request closed without merging**
