### PR TITLE
Merge upstream/master into v2

### PR DESCRIPTION
**Pull request by EricWF**
I'm submitting the PR simply to ensure the bots are happy with the merges.

### CODE REVIEW

**Comment by EricWF** [comment]
Hmm. Not sure how to get around the CLA problems here. Since the commits are already in master (or were in master), it should be OK to merge?

**Comment by dominichamon** [comment]
Um, I don't know. Yes, everything committed to master was done with a CLA in place. Unless maybe someone was able to remove their agreement after committing to master? I dunno...

**Comment by dominichamon** [comment]
You're going to need to get approvals for the following commits:

https://github.com/google/benchmark/commit/19048b7b65875e08c1e882e644a7a5f9bcfd3f82
https://github.com/google/benchmark/commit/e9a49be7f1fd6e3717687e42ad318957e8cd6c8e
https://github.com/google/benchmark/commit/ff2c255af5bb2fc2e5cd3b3685f0c6283117ce73

(and https://github.com/google/benchmark/commit/726a9bde2491ea226c1d7f84ea7cf9722edd2b94, but that's because of the others).

the users in question are @jwakely and @guoyr who apparently made those commits with email addresses that are no longer listed as current, or something similar.

I think we either need to have them update their emails on record to the ones in the commits, or do some sort of rebase where we ['edit' those commits](https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-one-specific-commit) and change the authorship.

**Comment by LebedevRI** [comment]
It might be simpler to go the other way around, and simply rebase the v2 branch on top of git master.

**Comment by jwakely** [comment]
I don't understand the problem with my email address, it's the same as it was when it got committed to master. My github account has several email addresses linked to it, including the ones used for these commits. My understanding is that I'm covered by Red Hat's corporate CLA via my membership of a particular group, I don't think I've signed an individual CLA with any email address.

**Comment by dominichamon** [comment]
going to explicitly make this abandoned.

**Pull request closed without merging**
