### PR TITLE
Drop unused mingw.py

### PR DESCRIPTION
**Pull request by cclauss**
Avoid Syntax Warning on Python 3.8: `3 is 3`  # —> Syntax Warning

### CODE REVIEW

**Comment by LebedevRI** [comment]
Is that script even used?
`$ grep -r mingw.py` suggests it's not.

**Comment by dominichamon** [comment]
Added in https://github.com/google/benchmark/commit/60910b3de7aa85ff28da14f34c7084711f99ac74. Idea was likely to use it in appveyor but it never was.

**Comment by LebedevRI** [comment]
Should we just drop that script?

**Comment by dominichamon** [comment]
i think so? unless it is useful for building an appveyor matrix.

**Comment by LebedevRI** [comment]
Thank you for bringing this up!

**Pull request merged**
