### PR TITLE
special treatment for DoNotOptimize using gcc with double long double

### PR DESCRIPTION
**Pull request by KlausLeppkes**
1.) I added 2 tests with assembly check into donotoptimize_assembly_test.cc.
2.) I tested successfully with g++ 9.2 and clang++9 on my machine.
3.) Using Intel C++ (ICC) 19.0.5.281 20190815, the current master as this branch fails:
	 63 - run_donotoptimize_assembly_test_CHECK (Failed)
	 64 - run_state_assembly_test_CHECK (Failed)
	 65 - run_clobber_memory_assembly_test_CHECK (Failed)

### CODE REVIEW

**Comment by dominichamon** [comment]
please take a look at the failures as they look legitimate.

**Comment by KlausLeppkes** [comment]
FileCheck was/is a new Tool for me. It's pretty cool to check the produced assembly btw. I will update the reference for clang in the next days.

**Comment by dominichamon** [comment]
@KlausLeppkes are you still planning to look into this or should i close it?

**Comment by dominichamon** [comment]
I should note that it is likely WAI that this only passes for some compiler/versions.

**Pull request closed without merging**
