### PR TITLE
Use EXPECT_DOUBLE_EQ when comparing doubles in tests.

### LINKED ISSUE #623: Build error on string_util_gtest.cc
With the latest commit, 7d03f2d , I'm seeing the following build error:

```
In file included from /home/developer/git/google/benchmark/test/string_util_gtest.cc:6:0:
/home/developer/git/google/benchmark/build/googletest/include/gtest/gtest.h: In instantiation of ‘testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = double; T2 = double]’:
/home/developer/git/google/benchmark/build/googletest/include/gtest/gtest.h:1460:64:   required from ‘static testing::AssertionResult testing::internal::EqHelper<lhs_is_null_literal>::Compare(const char*, const char*, const T1&, const T2&) [with T1 = double; T2 = double; bool lhs_is_null_literal = false]’
/home/developer/git/google/benchmark/test/string_util_gtest.cc:117:5:   required from here
/home/developer/git/google/benchmark/build/googletest/include/gtest/gtest.h:1432:11: error: comparing floating point with == or != is unsafe [-Werror=float-equal]
   if (lhs == rhs) {
           ^
```

### PR DESCRIPTION
**Pull request by dominichamon**
Fixes #623

### CODE REVIEW

**Comment by pleroy** [comment]
This PR makes me cry tears of blood.

When parsing any of the values in this test, which are all exactly representable in IEEE binary64, I surely hope that I get the *exact* value, not something fudged to within 4 ulps.

Now it appears that some genius at the FSF put in GCC a warning that says "don't compare floats for equality".  Could we please disable this warning?  There are circumstances where comparing for equality is fine, and this is one of them.  And if you don't know what you are doing, compiler warnings are not helping anyway.

For your enjoyment, here are some [words of wisdom](https://twitter.com/stephentyrone/status/856882266408202244) from @stephentyrone, who understands numerics much better than I ever will.

**Comment by LebedevRI** [comment]
Is it intentional that an external project (googletest) is being built with warnings?

**Comment by dominichamon** [comment]
Ahah, I wondered what was going on and why it hasn't failed in the past (or in my local builds). This is something I really hope clang doesn't embrace.

@LebedevRI I think this is not googletest being compiled with warnings, it's our test code being compiled with warnings (which is a good thing) and a macro being expanded from googletest.

Let me see if i can disable the warning (though i can't repro the issue locally to check).

**Comment by dominichamon** [comment]
Oh even better, we're enabling -Wfloat-equal.

**Comment by pleroy** [comment]
I blamed this line and I am looking sternly at @EricWF...

**Pull request merged**
