### PR TITLE
Support --benchmarks_filter in the compare.py 'benchmarks' command

### LINKED ISSUE #1484: [FR] Support compare.py benchmarks a.json b.json --benchmark_filter=blah
**Is your feature request related to a problem? Please describe.**

I've got an a.json and a b.json that took a while to collect due to lots of benchmarks and lots of repetitions.  I was surprised that

```
compare.py benchmarks a.json b.json --benchmark_filter=blah
```

Ignored `--benchmarks_filter=` and always displayed all the results.

**Describe the solution you'd like**

The "benchmarks" sub-command honors `--benchmarks_filter=` and reports as if only those benchmarks were run.

**Describe alternatives you've considered**

Post processing the benchmark .json before running compare.py is an inconvenient workaround.

### PR DESCRIPTION
**Pull request by matta**
Previously compare.py ignored the --benchmarks_filter argument when loading JSON.  This defeated any workflow when a single run of the benchmark was run, followed by multiple "subset reports" run against it with the 'benchmarks' command.

Concretely this came up with the simple case:

 compare.py benchmarks a.json b.json --benchmarks_filter=BM_Example

This has no practical impact on the 'filters' and
'benchmarkfiltered' comand, which do their thing at a later stage.

Fixes #1484

### CODE REVIEW

**Comment by matta** [comment]
This re-sends #1486. I deleted the branch in my fork and github didn't allow me to reopen the original PR even after I had recreated it.

**Comment by matta** [comment]
> This re-sends #1486. I deleted the branch in my fork and github didn't allow me to reopen the original PR even after I had recreated it.

Oh neat, github noticed the PR was based off the same hash and merged them. Still weird that I had to create a new branch name and resend the PR before realized that all I wanted to do was reopen the original PR.

**Comment by LebedevRI** [comment]
Looks reasonable. Test?

**Comment by LebedevRI** [comment]
@matta reverse ping :)
I'd prefer to have a test here, but a vague dismissive "nah, take it or leave it" could work too.

**Comment by matta** [comment]
Sorry Roman, this slipped my mind.  I'm not actively working on the project
I was using this for so it is unlikely I'll get to adding a test or
significantly tweaking this.  Is that vague/dismissive enough?  ;-)

**Comment by LebedevRI** [comment]
@dominichamon do we _need_ a test here?

**Comment by dominichamon** [comment]
need is a strong word.  i'd always prefer tests to avoid regressions, but i'd also rather have the feature than not.  your call, i trust your judgement.

**Review by dmah42 — APPROVED** [review]

**Comment by dmah42** [comment]
thanks!

**Pull request merged**
