### PR TITLE
Introduce CSV reporter

### PR DESCRIPTION
**Pull request by dominichamon**

### CODE REVIEW

**Comment by EricWF** [comment]
Both the names and the labels have to be quoted because they can contain commas. 
We also need to replace every occurrence of `"` in the label with `""`.

**Comment by dominichamon** [comment]
How can the names have commas? We generate the names from the benchmark functions.

i'll try to fix up the labels.

**Comment by EricWF** [comment]
The names can have commas in them if the benchmark function is a template.

```c++
template <class T, class U>
void BM_foo(benchmark::State& state);
// name: BM_foo<T, U>
```

**Comment by EricWF** [comment]
It is possible for the name field to include nested quotes as well (in very rare cases). Example:
```c++
template <char MyChar>
void BM_foo(benchmark::State& state);
BENCHMARK_TEMPLATE(BM_foo, '"');
```

**Comment by EricWF** [comment]
LGTM

**Pull request merged**
