### PR TITLE
Enable vectors in `DoNotOptimize`

### PR DESCRIPTION
**Pull request by goldsteinn**
Just a QOL change to make benchmarks vector code easier.

### CODE REVIEW

**Comment by LebedevRI** [comment]
Tests?

**Comment by goldsteinn** [comment]
> Tests?

Do you want aarch64 + x86_64, or is just x86_64 enough.

**Comment by LebedevRI** [comment]
> > Tests?
> 
> Do you want aarch64 + x86_64, or is just x86_64 enough.

I don't really know what kind of input variable type this targets
so i can't tell what exactly should be tested.
Can this be generically reached via clang vector types e.g.?

**Comment by goldsteinn** [comment]
> > > Tests?
> > 
> > 
> > Do you want aarch64 + x86_64, or is just x86_64 enough.
> 
> I don't really know what kind of input variable type this targets so i can't tell what exactly should be tested. Can this be generically reached via clang vector types e.g.?

Done, tests only compiled for gcc/clang.

**Comment by LebedevRI** [comment]
Some generic questions:
1. Has that asm constraint always been supported in every compiler version ever released?
2. What happens when it's used on other compilers? (MSVC?)
3. Does the order matter? Should it be `r,v,m` (i.e. mem being last)?

**Comment by goldsteinn** [comment]
> Some generic questions:
> 
> 1. Has that asm constraint always been supported in every compiler version ever released?
> 2. What happens when it's used on other compilers? (MSVC?)
> 3. Does the order matter? Should it be `r,v,m` (i.e. mem being last)?

Yeah, this patch is a bad idea. Its not super portable AFAICT (across compilers or arch within).

**Comment by LebedevRI** [comment]
Aha, so clang 3.9 didn't know that: https://godbolt.org/z/eP9zbjb4P
And even then, it's support is target dependent: https://godbolt.org/z/eP9zbjb4P
This, indeed, makes me uneasy about this feature, unfortunately...

**Pull request closed without merging**
