### PR TITLE
Remove std::is_trivially_destructible assertion. Fix issue #134.

### PR DESCRIPTION
**Pull request by EricWF**
See https://github.com/google/benchmark/issues/134

### CODE REVIEW

**Comment by theopolis** [comment]
Hi @EricWF, is there a problem with the CLA signing? It would be great to have this merged into benchmark's master ASAP!

**Comment by dominichamon** [comment]
this is really weird... @EricWF has committed in the past without any problems. I wonder if it's because his email changed so he has to resign the CLA.

**Comment by EricWF** [comment]
Sorry I've just been insanely busy with school, work and moving I haven't had a chance to work on this. I'll commit a fix tonight.

**Comment by dominichamon** [comment]
@EricWF are you planning more changes to this as suggested in #134, or is this fine to go in?

i'm concerned that we might access Now during termination as it is called from `StartTimer()` which is called by each thread. The only case this might be a problem is if the user sigkills so maybe we need to catch that and wait for `phase_condition_`?

**Comment by EricWF** [comment]
So I'll commit the change using a dynamic allocation because it clearly expresses intent. However because the type is trivially destructible I don't think it actually makes a semantic difference. Originally I thought avoiding dynamic allocation would prevent WallTimeImp from being wrapped in a static guard variable. However because WallTimeImp's constructor is not constexpr it will always have a static guard around it.

On another note I'm not convinced that the termination race condition is a real issue. You would have to call StartTimer from the destructor of a static object O, and where the construction of O was not sequenced before the first call to WallTimeImp. If your writing this kind of code your already screwed.

To be even more pedantic our fix still has undefined behavior in the case described above from the point of view of the standard. AFAIK accessing even a trivially destructible type after its destructors ran is UB.

**Pull request merged**
