### PR TITLE
[#766] add x-compile support for QNX

### LINKED ISSUE #766: add x-compile support for QNX SDP
Since googletest already supports x-compilation for QNX, it is nice to have google benchmark support it too.

### PR DESCRIPTION
**Pull request by jilinzhou**
Since googletest already supports QNX, it is nice to have it for google benchmark also.
Fixes #766

### CODE REVIEW

**Comment by jilinzhou** [comment]
I signed it!

**Comment by jilinzhou** [comment]
What does this mean:

```
unzip:  cannot find zipfile directory in one of bazel-installer.sh or
        bazel-installer.sh.zip, and cannot find bazel-installer.sh.ZIP, period.
/home/travis/.travis/functions: line 524:  7496 Terminated              travis_jigger "${!}" "${timeout}" "${cmd[@]}"
The command "if [ "${TRAVIS_OS_NAME}" == "linux" ]; then sudo apt-get update -qq; sudo apt-get install -qq unzip; wget https://github.com/bazelbuild/bazel/releases/download/0.10.1/bazel-0.10.1-installer-linux-x86_64.sh --output-document bazel-installer.sh; travis_wait sudo bash bazel-installer.sh; fi" failed and exited with 9 during .
```

**Comment by dominichamon** [comment]
looks like a bad bazel installation on one of the build bots. Nothing related to your change.

cla-bot doesn't seem to agree you signed it. can you make sure that the commits are under the same email address as the one you used to sign the CLA? thanks.

**Comment by LebedevRI** [comment]
You want to be rebasing your master branch, and rebasing the feature branches ontop of your master branch. That way the branch history is clean.

**Pull request closed without merging**
