### PR TITLE
Always use inline asm DoNotOptimize with clang.

### PR DESCRIPTION
**Pull request by mwinterb**
clang-cl masquerades as MSVC but not GCC, so it was using the
MSVC-compatible definitions of DoNotOptimize and ClobberMemory.
Presumably, it's better in general to use the targeted assembly for
this functionality (the codegen is different), but the specific issue
is that clang-cl deprecates the usage of _ReadWriteBarrier, and this
gets rid of that warning.

### CODE REVIEW

**Comment by EricWF** [comment]
This LGTM, but could you push a dummy commit to re-trigger the Appveyor bot? I think the failure was spurious.

**Comment by mwinterb** [comment]
Well, this is bothersome.

**Comment by dominichamon** [comment]
It may be unrelated to your change. one second while i check.

**Comment by dominichamon** [comment]
Yes. this is happening already. i'll merge this now (and fix the appveyor test i guess).

**Comment by dominichamon** [comment]
thank you!

**Comment by mwinterb** [comment]
Thank you.

**Pull request merged**
