### PR TITLE
Include the benchmark's family-name in State

### PR DESCRIPTION
**Pull request by oontvoo**
For compat with internal library, where State::name() returns the benchmark's family name.

### CODE REVIEW

**Comment by dominichamon** [comment]
can you add tests please?

**Comment by nicholasjng** [comment]
Would you consider adding this to the Python API as well? That would require one fewer parses of the benchmark name into family and arguments :)

**Comment by dmah42** [comment]
perfcounter failures are unrelated (seems like an apt server is down)

**Comment by dmah42** [comment]
merging this as is, but i agree Python bindings would be nice to have.

**Pull request merged**
