### PR TITLE
Updates for inclusive language

### PR DESCRIPTION
**Pull request by messerb5467**
With moves towards inclusive language:
https://www.ibm.com/blogs/think/2020/08/words-matter-driving-thoughtful-change-toward-inclusive-language-in-technology/
we'd like to contribute the changes shown in this PR back to the community for greater acceptance. The particular reason for this
change is sanity is becoming an offensive word towards neurodiverse individuals.

### CODE REVIEW

**Comment by dominichamon** [comment]
thanks so much for this contribution. i'm happy to merge this if you can sign the CLA.

**Comment by messerb5467** [comment]
Sweet thanks. I'm working through the CLA administriva with a couple contacts now and will get back to you asap

**Comment by messerb5467** [comment]
Just to bump this thread, we're moving forward in it. Still some administriva to work through.

**Comment by messerb5467** [comment]
@dominichamon The code is now ready to go. Thanks for your help!

**Comment by dominichamon** [comment]
thank you!

**Comment by HorribleCppGuru** [comment]
👍🏿 as a Black trans woman, I still feel that this entire repository is traumatizing, as any sort of evaluation and quantification of performance is inherently white supremacist in philosophy. They used to "benchmark" my ancestors... so Google u either give me some sort of GitHub badge or else.

**Pull request merged**
