### PR TITLE
Add _build to gitignore to enable out-of-source builds

### PR DESCRIPTION
**Pull request by dominichamon**

### CODE REVIEW

**Comment by ckennelly** [comment]
Is there a reason to prefer `_build` to `build`, etc.?

**Comment by dominichamon** [comment]
no reason to prefer anything in particular. i've always used _build.

**Comment by EricWF** [comment]
Any reason not to put both in there?

**Comment by dominichamon** [comment]
added both, and added comments.

**Comment by EricWF** [comment]
LGTM. Deleting branch.

**Pull request merged**
