### PR TITLE
Fix MSVC++ command line warnings and support RELWITHDEBINFO / MINSIZEREL builds

### PR DESCRIPTION
**Pull request by BillyONeal**
Making this again backed by a separate branch instead of my master. (oops)

### CODE REVIEW

**Comment by dominichamon** [comment]
if appveyor would run against pull requests it would make me so happy.

**Comment by dominichamon** [comment]
so.. this looks fine to me, but i'm mostly flying blind. given travis doesn't break, and appveyor doesn't want to run until things are merged i guess i'll just go ahead and merge it :D

**Comment by BillyONeal** [comment]
@dominichamon I set up Appveyor in my fork and it built successfully here: https://ci.appveyor.com/project/BillyONeal/benchmark/build/4

**Comment by dominichamon** [comment]
perfect. thanks, @BillyONeal

**Comment by EricWF** [comment]
@BillyONeal :-(

Just because I'm bragging about libc++ on Windows doesn't mean I know what I'm doing. I trust that this is the right configuration for MSVC, but I'm curious as to why the CMake default flags don't correctly handle it?

@BillyONeal Mind pushing an updated version of this change to get the bots going?

**Pull request merged**
