### PR TITLE
Appended additional BSD 3-Clause to LICENSE

### PR DESCRIPTION
**Pull request by oontvoo**
Needed for export_header module

### CODE REVIEW

**Comment by dominichamon** [comment]
thanks

**Comment by LebedevRI** [comment]
This change seems to be missing about 500 words of motivation.

**Comment by LebedevRI** [comment]
(I would recommend reverting this immediately)

**Comment by oontvoo** [comment]
This was needed because PR/1321 included code that had this license (the generate_export_header).
This change should have been done there but I guess we didn't have a git license compliant-lint check.

**Comment by LebedevRI** [comment]
This change should be a lot more explicit about that, it should call out that said new license is only for that single specific file,
otherwise this can be read as if the whole project is now double-licensed. This is a problem.

**Comment by dominichamon** [comment]
why would it be a problem that the project as a whole is double-licensed under these licenses, which are completely compatible?

**Comment by LebedevRI** [comment]
> why would it be a problem that the project as a whole is double-licensed under these licenses, which are completely compatible?

Please consult a lawyer.
Until then, please revert this.

**Comment by LebedevRI** [comment]
> This change should be a lot more explicit about that, it should call out that said new license is only for that single specific file, otherwise this can be read as if the whole project is now double-licensed. This is a problem.

**Comment by oontvoo** [comment]
@LebedevRI  I've sent PR/1366 . PTAL. Thanks!

**Comment by oontvoo** [comment]
from my interpretation, LebedevRI's concern is that it's not OK to retrospectively re-license code (which is what this PR sort of accidentally did). I think that's a reasonable point.

**Pull request merged**
