### PR TITLE
Begin JSON reporter change: Allow users to specify arbitrary JSON input/output.

### PR DESCRIPTION
**Pull request by EricWF**
This patch begins a set of changes to convert the library to use JSON as
the primary data type used to communicate with users; but for custom user
input and output.

The patch introduces the json.h header taken, and modified, from
https://github.com/nlohmann/json . The header was modified to no
longer use the namespace nlohmann, nor any macros containing NLOHMANN
so as to not interfere with other users who already incidentally
use this header.

Additionally, this patch adds `Benchmark::WithInput` to allow
the passing of arbitrary JSON as an input argument to a benchmark.
The results of which can be accessed using `State::GetInput()`.

This patch also adds `State::operator[](std::string)`, which allows
users to report arbitrary JSON as output from a benchmark. See
the documentation for examples.

### CODE REVIEW

**Comment by EricWF** [comment]
@pleroy Here is the first set of changes I'm proposing in order to move toward  using JSON as the primary format.

**Comment by EricWF** [comment]
The coverage decrease is very likely caused by the introduction of the new header, which we aren't testing.

**Comment by dominichamon** [comment]
the json header you're using is licensed under MIT. This means we'd have to update our license to indicate that the software is now multiple-licensed.

Can we instead depend on this JSON library in some other way (submodules, findpackage (it uses cmake)) which would also give us the opportunity to get updates?

**Comment by biojppm** [comment]
Hey @EricWF,

The unit tests I wrote for the counters are currently reading their data from the CSV output. This will need to be changed as well. FWIW I can move that logic to JSON if it helps.

**Comment by EricWF** [comment]
@biojppm I was planning on converting the tests myself in a later commit, since it's a good opportunity for me to demonstrate how I believe the API should be used and tested.

**Comment by EricWF** [comment]
Urg. This Google bot thing is going to be a problem using the v2 branch.

**Pull request merged**
