### PR TITLE
Revert "Add possibility to ask for libbenchmark version number (#1004)"

### PR DESCRIPTION
**Pull request by dominichamon**
Reverts google/benchmark#1403

due to two reported bugs:

version status has nothing useful (not a git checkout) and
#1416

### CODE REVIEW

**Comment by dominichamon** [comment]
@Matthdonau sorry for reverting your work.  feel free to revert the revert and make the improvements necessary to make this work:

1. instead of exiting when we don't get a git version, we should return the default (l74-ish of the python script).
2. figure out why cmake embedding fails... maybe we don't export the version.h correctly?

**Comment by Matthdonau** [comment]
Regarding 1: I think I don't understand. What you describe is what should happen. if no git is available or we are not in a git checkout the default project version (currently 1.6.1) is used.
Regarding 2: @dominichamon I suspect the problem is that the version.h header is generated in CMAKE_BINARY_DIR while PROJECT_BINARY_DIR would be correct

**Comment by dominichamon** [comment]
> Regarding 1: I think I don't understand. What you describe is what should happen. if no git is available or we are not in a git checkout the default project version (currently 1.6.1) is used.

l71 .. we exit. we don't return the default. this is being tickled when using snapshot zip releases I think.

> Regarding 2: @dominichamon I suspect the problem is that the version.h header is generated in CMAKE_BINARY_DIR while PROJECT_BINARY_DIR would be correct

ah maybe. we should do whatever the other generated header is doing as that seems to work.

**Comment by Matthdonau** [comment]
I made a PR. The problem is: If there is no volatile-status.txt there is no default version to default to. Is this really the issue here or is it the issue I fixed in the PR?

**Pull request merged**
