### PR TITLE
Add macros for create benchmark with templated fixture

### PR DESCRIPTION
**Pull request by onto**
Example:
```cpp
template<typename Mutex>
struct MutexTest : public benchmark::Fixture
{
    Mutex mutex;
};

BENCHMARK_TEMPLATE_DEFINE_F(MutexTest, Mutex, std::mutex)(benchmark::State& state)
{
    while (state.KeepRunning())
    {
        std::lock_guard<std::mutex> locker(mutex);
    }
}

BENCHMARK_TEMPLATE_DEFINE_F(MutexTest, TimedMutex, std::timed_mutex)(benchmark::State& state)
{
    while (state.KeepRunning())
    {
        std::lock_guard<std::timed_mutex> locker(mutex);
    }
}

BENCHMARK_REGISTER_F(MutexTest, Mutex)->ThreadRange(1,8);
BENCHMARK_REGISTER_F(MutexTest, TimedMutex)->ThreadRange(1,8);
```

### CODE REVIEW

**Comment by onto** [comment]
I signed it!

**Comment by dominichamon** [comment]
Can you add your example, or something representative, to one of the test files? Also, please update the documentation with a section on using these macros.

**Comment by onto** [comment]
Tests added, documentation updated

**Comment by dominichamon** [comment]
Awesome! thank you :)

**Pull request merged**
