### PR TITLE
Add output format to ConsoleReporter with support for CSV

### PR DESCRIPTION
**Pull request by dominichamon**

### CODE REVIEW

**Comment by EricWF** [comment]
Silly Googlebot. Anyway what is the rational for not making this another class? If we add more formats (ie JSON) it seems like ConsoleReporter could become needlessly complicated to support them all.

**Comment by dominichamon** [comment]
Well, we could. But I thought this was a quick way to extend it to support a new format, then we can look at the surface area of the changes (printing the header and run data) and then bump the ConsoleReporter to a base class with TableReporter and CSVReporter (and JSONReporter) as subclasses.

Do you think it's worth doing that jump now?

**Comment by EricWF** [comment]
I don't think we need to make that jump now but I wanted to ask.

**Comment by pphaneuf** [comment]
Heh, rather hilariously, @dominichamon's CLA doesn't appear to have been migrated to the new system. :smiley: 

I *know* you signed it in the old system, could you re-sign it in the new one? Silly, I know, sorry...

https://cla.developers.google.com/

**Comment by dominichamon** [comment]
I could ... or we could wait until Monday when I'll be a Google employee again :P

**Comment by pphaneuf** [comment]
Okay, now that is **properly** hilarious!

Welcome back, I guess... :smiley:

**Comment by EricWF** [comment]
I don't know a lot about CSV, but I think templated benchmarks might cause problems with the output because the benchmark name may contain commas. Ex BM_myTest<Foo, Bar>.

Can you comment on this?

**Comment by dominichamon** [comment]
closing as a CSVreporter along the lines of #100 will be better.

**Pull request closed without merging**
