### PR TITLE
Fixing issue with ARM64EC and MSVC

### PR DESCRIPTION
**Pull request by jbr-smtg**
The goal of this pull request is to allow the detection of MSVC's ARM64EC as if it is ARM64.

See: https://learn.microsoft.com/en-us/windows/arm/arm64ec

Thanks in advance for your review!

### CODE REVIEW

**Comment by dmah42** [comment]
sorry, i can't look at the PR until you've signed the CLA.  would you mind?

**Comment by jbr-smtg** [comment]
Hi @dmah42,
The CLA is already signed from my side.
See  image.
Unless something was not done correctly?

**Comment by dmah42** [comment]
oh sorry, i didn't see that.  i checked in my cla tool and it didn't find you, but i think your email is there. i should just trust the robot.

**Comment by jbr-smtg** [comment]
No worries, many thanks for checking!

**Review by dmah42 — APPROVED** [review]

**Comment by dmah42** [comment]
thank you!

**Pull request merged**
