### PR TITLE
Cleaner UserCounter interface (instead of typedef std::map)

### PR DESCRIPTION
**Pull request by dominichamon**
I think this is cleaner, but I'm also open to the notion it might be extra abstraction with no benefit.

### CODE REVIEW

**Comment by gnarlie** [comment]
Moving the implementation of UserCounters to the .cc file would likely fix #420 as well.

**Comment by EricWF** [comment]
I'm not sure I think this is an improvement. People know and understand the STL interface and I think it's a benefit to offer it directly.

**Comment by dominichamon** [comment]
I'm wary of users accidentally breaking user counters by (ab)using the map
interface. This is also inspired in part by #420.

Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*

**Comment by EricWF** [comment]
> I'm wary of users accidentally breaking user counters by (ab)using the map
interface. 

That feels like a "Doctor, it hurts when I do this" situation, where users are free to make their lives difficult for themselves.

Your suggested interface was a part of the original review, but was removed for a number of reasons. One in particular being when you want to be able to change the value of an existing counter without having to always lookup up the key in the map. Ex:

```
static void BM_Foo(benchmark::State &S) {
  auto &CounterRef = (S.counters["foo"] = 42);
  while (S.KeepRunning()) {
    int Res = Foo();
    CounterRef += Res;
  } 
}
```

> This is also inspired in part by #420.

I don't think this will have an affect on #420, since the `std::map` definitions will still be in `libbenchmark.a` and will be visible during link time.

**Comment by dominichamon** [comment]
fair enough :)

**Pull request closed without merging**
