### PR TITLE
Revert "Implementation of random interleaving.  (#1105)"

### PR DESCRIPTION
**Pull request by dominichamon**
This reverts commit a6a738c1cc3b754f1bccc0cefc3aeb551c341f88.

### CODE REVIEW

**Review by LebedevRI — APPROVED** [review]
:(

**Comment by chfast** [comment]
Why?

**Comment by LebedevRI** [comment]
> Why?

I guess, the description should have at least linked to the disscussion in https://github.com/google/benchmark/pull/1105#issuecomment-851056242

I'll try to take a look, i think at least the pure interleaving part should be easy..

**Comment by dominichamon** [comment]
> Why?

Please see the comments left on #1105. Essentially, it broke some expectations around how mintime and repetition flags work causing some existing runs to take 10x longer than expected. It's fixable, but I'd rather get the broken experience out of HEAD first.

**Pull request merged**
