### PR TITLE
Add command line option to print user counters in tabular format

### PR DESCRIPTION
**Pull request by biojppm**
This PR adds the option `--benchmark_counters_tabular={true|false}`, which makes the ConsoleReporter print the user counters in tabular format. The option defaults to false. This follows discussions in PR #262 (notably [this](https://github.com/google/benchmark/pull/262#issuecomment-244257349) and [this](https://github.com/google/benchmark/pull/262#issuecomment-248969221)).

To be clear:

- by default, counters are printed at the end, the same way as bytes_processed and items_processed, as agreed in #262 .  This is best for cases in which there are few counters, or where there are only a couple of lines per benchmark.
- when `--benchmark_counters_tabular=true` is given, then the counters are printed as a column of the table. This is best for cases in which there are a lot of counters, or a lot of lines per benchmark.

Here's an example comparison between the two versions (Note that I removed some whitespace from both examples).

First the default `--benchmark_counters_tabular=false`:

```
------------------------------------------------------------------------------
Benchmark                        Time           CPU Iterations UserCounters...
------------------------------------------------------------------------------
BM_UserCounter/threads:8      2248 ns      10277 ns      68808 Bar=16 Bat=40 Baz=24 Foo=8
BM_UserCounter/threads:1      9797 ns       9788 ns      71523 Bar=2 Bat=5 Baz=3 Foo=1024m
BM_UserCounter/threads:2      4924 ns       9842 ns      71036 Bar=4 Bat=10 Baz=6 Foo=2
BM_UserCounter/threads:4      2589 ns      10284 ns      68012 Bar=8 Bat=20 Baz=12 Foo=4
BM_UserCounter/threads:8      2212 ns      10287 ns      68040 Bar=16 Bat=40 Baz=24 Foo=8
BM_UserCounter/threads:16     1782 ns      10278 ns      68144 Bar=32 Bat=80 Baz=48 Foo=16
BM_UserCounter/threads:32     1291 ns      10296 ns      68256 Bar=64 Bat=160 Baz=96 Foo=32
BM_UserCounter/threads:4      2615 ns      10307 ns      68040 Bar=8 Bat=20 Baz=12 Foo=4
BM_Factorial                    26 ns         26 ns   26608979 40320
BM_Factorial/real_time          26 ns         26 ns   26587936 40320
BM_CalculatePiRange/1           16 ns         16 ns   45704255 0
BM_CalculatePiRange/8           73 ns         73 ns    9520927 3.28374
BM_CalculatePiRange/64         609 ns        609 ns    1140647 3.15746
BM_CalculatePiRange/512       4900 ns       4901 ns     142696 3.14355
```

... compared to the tabular version `--benchmark_counters_tabular=true`. Note the additional printing of the header. This will happen any time the counter set changes.

```
---------------------------------------------------------------------------------------
Benchmark                        Time           CPU Iterations    Bar   Bat   Baz   Foo
---------------------------------------------------------------------------------------
BM_UserCounter/threads:8      2198 ns       9953 ns      70688     16    40    24     8
BM_UserCounter/threads:1      9504 ns       9504 ns      73787      2     5     3     1
BM_UserCounter/threads:2      4775 ns       9550 ns      72606      4    10     6     2
BM_UserCounter/threads:4      2508 ns       9951 ns      70332      8    20    12     4
BM_UserCounter/threads:8      2055 ns       9933 ns      70344     16    40    24     8
BM_UserCounter/threads:16     1610 ns       9946 ns      70720     32    80    48    16
BM_UserCounter/threads:32     1192 ns       9948 ns      70496     64   160    96    32
BM_UserCounter/threads:4      2506 ns       9949 ns      70332      8    20    12     4
--------------------------------------------------------------
Benchmark                        Time           CPU Iterations
--------------------------------------------------------------
BM_Factorial                    26 ns         26 ns   26392245 40320
BM_Factorial/real_time          26 ns         26 ns   26494107 40320
BM_CalculatePiRange/1           15 ns         15 ns   45571597 0
BM_CalculatePiRange/8           74 ns         74 ns    9450212 3.28374
BM_CalculatePiRange/64         595 ns        595 ns    1173901 3.15746
BM_CalculatePiRange/512       4752 ns       4752 ns     147380 3.14355
BM_CalculatePiRange/4k       37970 ns      37972 ns      18453 3.14184
BM_CalculatePiRange/32k     303733 ns     303744 ns       2305 3.14162
BM_CalculatePiRange/256k   2434095 ns    2434186 ns        288 3.1416
BM_CalculatePiRange/1024k  9721140 ns    9721413 ns         71 3.14159
BM_CalculatePi/threads:8      2255 ns       9943 ns      70936
```

### CODE REVIEW

**Comment by EricWF** [comment]
Can you make sure to squash your commits before sending a PR? This PR currently has 80 different commits as part of it and that seems entirely unnecessary.

**Comment by biojppm** [comment]
?? I don't know why the commits from #262 are shown here... really, this PR is only two commits or so from the tip. Anyway.

**Comment by biojppm** [comment]
@EricWF can you give me some pointers in how to do that? I was under the impression that pulling the upstream was enough.

**Comment by EricWF** [comment]
When you pull from upstream it doesn't overwrite your local commit history, it simply merges or re-bases your local commits on top of the upstream commits.

Personally I would do something like this:
(Disclaimer: I'm not responsible for anything bad git does)

```
# Reset your commit history to match upstream/master. All changes not committed to upstream will
# will now be in staging.
git reset --soft upstream/master

# Re-commit all of the staged changes as a single commit.
git commit -am "my commit message"

# Push the commits to github
git push --force

```

**Comment by biojppm** [comment]
Maybe this is because when I did these two commits, 262 was not yet merged into the upstream? I'm gonna try to make it so that it looks like I did a branch off of today's upstream. If it doesn't work, I'll do the reset as you suggest.

**Comment by biojppm** [comment]
@EricWF It did not work.

**Comment by biojppm** [comment]
Moved this to #350

**Pull request closed without merging**
