### PR TITLE
HumanReadableNumber(): Simplify output for simple numbers. Examples:

### PR DESCRIPTION
**Pull request by biojppm**
```
HumanReadableNumber(    0.0)=      0    ---->         0
HumanReadableNumber(    0.5)=   512m    ---->       0.5
HumanReadableNumber(    0.9)= 921.6m    ---->       0.9
HumanReadableNumber(    1.0)=  1024m    ---->         1
HumanReadableNumber(   1.05)=1075.2m    ---->      1.05
HumanReadableNumber(    1.1)=    1.1    ---->       1.1
HumanReadableNumber(    1.2)=    1.2    ---->       1.2
HumanReadableNumber( 0.5e-1)=  51.2m    ---->      0.05
HumanReadableNumber( 0.9e-1)= 92.16m    ---->      0.09
HumanReadableNumber( 1.0e-1)= 102.4m    ---->       0.1
HumanReadableNumber(1.05e-1)=107.52m    ---->     0.105
HumanReadableNumber( 1.1e-1)=112.64m    ---->      0.11
HumanReadableNumber( 1.2e-1)=122.88m    ---->      0.12
HumanReadableNumber( 0.5e-3)=524.288u   ---->   524.288u
HumanReadableNumber( 0.9e-3)=943.718u   ---->   943.718u
HumanReadableNumber( 1.0e-3)=1048.58u   ---->   1048.58u
HumanReadableNumber(1.05e-3)=  1101u    ---->   0.00105
HumanReadableNumber( 1.1e-3)=1.1264m    ---->    0.0011
HumanReadableNumber( 1.2e-3)=1.2288m    ---->    0.0012
```

### CODE REVIEW

**Comment by dominichamon** [comment]
if we're going to use u for micro (and n for nano, etc) then why would we not use m for milli?

i'm not sure this makes things clearer.

**Comment by biojppm** [comment]
This PR tries to make simple numbers more readable, not to remove the m for milli.

To be clear, I'll highlight some examples for the current output of HumanReadableNumber:
```
0.9  -> 921.6m
1    -> 1024m
1.05 -> 1075.2m
```
This is arguably less human readable than the original. Hence this PR, which makes HumanReadableNumber() output 1, 0.9 and 1.05 for the examples above.

Now, above (line 49), I've used 0.001 as a threshold. This covers the "m" range as you point out. I chose this as the 1024 base will also arguably end up making the result less readable. But I accept that here the advantage is less clear. Let's compare the current state vs thresholds of 0.001 and 0.01:
```
---------------------------------------------------------------
                             current   |thresh=0.001|thresh=0.01
---------------------------------------------------------------
HumanReadableNumber(    0.0)=      0   |        0   |        0 
HumanReadableNumber(    0.5)=   512m   |      0.5   |      0.5 
HumanReadableNumber(    0.9)= 921.6m   |      0.9   |      0.9 
HumanReadableNumber(    1.0)=  1024m   |        1   |        1 
HumanReadableNumber(   1.05)=1075.2m   |     1.05   |     1.05 
HumanReadableNumber(    1.1)=    1.1   |      1.1   |      1.1 
HumanReadableNumber(    1.2)=    1.2   |      1.2   |      1.2 
HumanReadableNumber( 0.5e-1)=  51.2m   |     0.05   |     0.05 
HumanReadableNumber( 0.9e-1)= 92.16m   |     0.09   |     0.09 
HumanReadableNumber( 1.0e-1)= 102.4m   |      0.1   |      0.1 
HumanReadableNumber(1.05e-1)=107.52m   |    0.105   |    0.105 
HumanReadableNumber( 1.1e-1)=112.64m   |     0.11   |     0.11 
HumanReadableNumber( 1.2e-1)=122.88m   |     0.12   |     0.12 
HumanReadableNumber( 0.5e-3)=524.288u  |  524.288u  |  524.288u
HumanReadableNumber( 0.9e-3)=943.718u  |  943.718u  |  943.718u
HumanReadableNumber( 1.0e-3)=1048.58u  |  1048.58u  |  1048.58u
HumanReadableNumber(1.05e-3)=  1101u   |  0.00105   |    1101u 
HumanReadableNumber( 1.1e-3)=1.1264m   |   0.0011   |  1.1264m <--------
HumanReadableNumber( 1.2e-3)=1.2288m   |   0.0012   |  1.2288m <--------
```
Would you be fine with threshold=0.01? You would still get the millis for values lower than 0.01.

**Comment by biojppm** [comment]
FWIW, this PR was motivated by the following situation:
```
--------------------------------------------------------------------
Benchmark                     Time      CPU Iterations    Bar    Foo
--------------------------------------------------------------------
BM_UserCounter/threads:8   2198 ns  9953 ns      70688     16      8
BM_UserCounter/threads:1   9504 ns  9504 ns      73787      2  1024m <------- was expecting 1!
BM_UserCounter/threads:2   4775 ns  9550 ns      72606      4      2
BM_UserCounter/threads:4   2508 ns  9951 ns      70332      8      4
BM_UserCounter/threads:8   2055 ns  9933 ns      70344     16      8
BM_UserCounter/threads:16  1610 ns  9946 ns      70720     32     16
BM_UserCounter/threads:32  1192 ns  9948 ns      70496     64     32
BM_UserCounter/threads:4   2506 ns  9949 ns      70332      8      4
```
In the second row, I was expecting the value of Foo to be 1 but I get 1024m...

**Comment by biojppm** [comment]
@dominichamon if you think there's no merit to this PR, just let me know and I'll close it. I'm not insisting here -- just trying to see whether you've been short on time to revisit this or just have no interest.

**Comment by dominichamon** [comment]
Purely short on time. i'll take another look.

**Comment by dominichamon** [comment]
threshold 0.01 looks better for this case at least:
```
HumanReadableNumber(1.05e-3)=  1101u   |  0.00105   |    1101u 
```

**Comment by dominichamon** [comment]
thank you! and sorry for the delay.

**Pull request merged**
