### PR TITLE
Bind more State methods/attributes to Python

### PR DESCRIPTION
**Pull request by AntoinePrv**
Hi,

The following PR binds more of the `State` methods in Python.
  - Bind `Counter::Flags` and bind `operator|`
  - Bind `Counter::OneK`
  - Bind `Counter`
  - Make Counter implicitly constructible from `float`, `int`
  - Bind some more `State` methods
  - Bind `State::counters` making it possible to use `state.counters["foo"] = 42` and `state.counters["foo"] = Counter(42, Counter.kIsRate)`...

However, there remains a number of questions:
  - [ ] Explicit the naming convention for function.methods? Python typically uses `snake_case`, which seems to have been done for methods but not functions
  - [ ] Define a test strategy/framework. This is hard because `State` are not constructible without registering a benchmark and running the main function.

### CODE REVIEW

**Comment by AntoinePrv** [comment]
@googlebot I signed it!

**Comment by dominichamon** [comment]
It's not really a testing strategy, but having these new features in `example.py` can help document them (and running that will test them in a way... at least ensure the syntax is correct everywhere).

**Comment by AntoinePrv** [comment]
Thanks, I will add these in the example file. Is the file run in CI? If not it could be a good addition, but I'm not sure I'm the best person to contribute for this.

**Comment by AntoinePrv** [comment]
I added some more example to the files.
Some methods are not added to the example because they are meaningless without #1038.

I also noticed that `state.range()` segfaults when there is no range. In C++ there is an `assert` but this does not work in Python.
To avoid this, we could create and expose a `State.range_size()`, and add a runtime check that the range is not empty.

**Comment by dominichamon** [comment]
> Thanks, I will add these in the example file. Is the file run in CI? If not it could be a good addition, but I'm not sure I'm the best person to contribute for this.

it isn't. it likely should be :)

**Comment by dominichamon** [comment]
Thanks for the extra examples, and the formatting changes. It looks like it now follows https://google.github.io/styleguide/pyguide.html#s3.4-indentation ?

**Comment by AntoinePrv** [comment]
I ran [Black](https://github.com/psf/black) because the former formatting seemed far from Python convention.
In hindsight, it seems to fit most of the Google style guide. Perhaps the line length default to 88 is a bit over Google's.

**Comment by dominichamon** [comment]
i added a pylint (fatal) check to our CI but i had to reformat some things. you have some conflicts now just from the formatting but i'll see if i can take care of that as it's my fault.

**Comment by dominichamon** [comment]
LGTM. travis looks unrelated (not sure why `ctest` is expanding to `bazel test` instead of `make test`).

**Pull request merged**
