### PR TITLE
Removed deprecated function

### PR DESCRIPTION
**Pull request by oontvoo**

### CODE REVIEW

**Comment by dominichamon** [comment]
should i do a release before we land this?

**Comment by oontvoo** [comment]
Yeah, I think that would make sense given this may break existing code. (Internally, there is only one user of this ... not sure about external users). Thanks!

**Comment by dominichamon** [comment]
v1.7.1 created

**Review by dominichamon — APPROVED** [review]

**Comment by dominichamon** [comment]
thanks for the cleanup

**Pull request merged**
