### PR TITLE
Update nanobind_bazel to v2.2.0

### PR DESCRIPTION
**Pull request by nicholasjng**
Adds support for free-threaded nanobind extension builds, though we don't currently build a free-threaded wheel.

### CODE REVIEW

**Comment by nicholasjng** [comment]
Since Python 3.13 has been released, I'll also add it to cibuildwheel and the Python bindings test matrix shortly if that's ok with you.

**Comment by dmah42** [comment]
looks like googletest got accidentally upgraded (WARNING: For repository 'com_google_googletest', the root module requires module version googletest@1.12.1, but got googletest@1.14.0 in the resolved dependency graph.)

amongst others:

WARNING: For repository 'bazel_skylib', the root module requires module version bazel_skylib@1.5.0, but got bazel_skylib@1.7.1 in the resolved dependency graph.
WARNING: For repository 'platforms', the root module requires module version platforms@0.0.8, but got platforms@0.0.10 in the resolved dependency graph.
WARNING: For repository 'rules_python', the root module requires module version rules_python@0.31.0, but got rules_python@0.37.0 in the resolved dependency graph.
WARNING: For repository 'com_google_googletest', the root module requires module version googletest@1.12.1, but got googletest@1.14.0 in the resolved dependency graph.

we might want to do an explicit upgrade before this can land.

**Comment by dmah42** [comment]
#1867 should do it

**Comment by nicholasjng** [comment]
Sure. Is there another version before their latest C++17 upgrade? Otherwise this might have to wait for the upgrade to C++17.

**Review by dmah42 — APPROVED** [review]

**Comment by dmah42** [comment]
thank you for your continued maintenance of this dark corner of the project!

**Pull request merged**
