### PR TITLE
Port to Windows 7/Visual Studio 2013

### PR DESCRIPTION
**Pull request by pleroy**
Apologies for the size of this pull request but it seems hard to split it in a meaningful way.

In porting the benchmark library I have tried to follow the model used by `glog`, and I have lifted some code from there.  Here is an overview of the changes:

1. Add a subdirectory `msvc/` containing the MS project and solution files.  There is one project for the library (`google-benchmark`) and one project for the tests (`google-benchmark-test`).  This stuff is just humongous blobs of automatically-generated XML, not much to review.
1. Change `.gitignore` and `.gitattributes` to properly handle the MSVC artifacts.
1. Add a `src/port.h` file (and the corresponding `src/port.cc`) to factor out the differences between Windows and the various Unix-ish OSes.  I lifted this file from `glog` and did the necessary adjustments.  In particular, it defines a bunch of `HAVE_` symbols that act as a poor man's `config.h`.  `src/port.h` must be included early in every source file that has OS dependencies, as among other things it defines the all-important symbols `OS_WINDOWS` and `COMPILER_MSVC`.
1. Change a bunch of includes to make them depend on the `HAVE_` symbols.
1. Implement `MyCPUUsage` for Windows.  No `ChildrenCPUUsage` yet.
1. Add a `pthread` library for Windows in `src/windows/pthread.{h,cc}`.  I got this library from http://locklessinc.com/articles/pthreads_on_windows/.  I did minimal changes to make it compile (mostly fixing casts) and I separated it into `.h` and `.cc` files instead of having everything in the `.h` file (which caused linker errors).  This library is distributed under a 3-clause BSD licence so I am assuming that using it is not problematic.
1. Other than porting, I made two significant changes to the code of the benchmark library:
  * In  `BenchmarkFamilies::RemoveBenchmark` I commented out some code which was changing a vector while iterating over it.
  * In `State::FinishInterval` I turned a `CHECK` into a warning because the wall time clock has poor accuracy on Windows 7.

### CODE REVIEW

**Comment by izaid** [comment]
Can I ask what the status is on this? What needs to be done to make it work?

**Comment by mattyclarkson** [comment]
@izaid, I've done some porting to MinGW over at #64. That branch just needs a little bit more to get working on VS. Haven't had any time to do it recently though.

**Comment by EricWF** [comment]
With the recent and large scale changes to just about all the code I don't think this patch is going to merge in any meaningful way.

Is there anybody that is willing to continue on with this work?

**Comment by mattyclarkson** [comment]
@EricWF, I'm keen to get the benchmarking library to work on Windows. I wrote a thinner MinGW port branch #64 but have been swamped with other stuff. I can try to have a look soon. I'll have to get reacquainted with the recent changes that have gone in though. Probably best to close both and create an issue for Windows support and wait for someone to pick it up?

**Comment by EricWF** [comment]
The MinGW port in #64 looks reasonable. Lets try and get that in soon.

**Comment by pleroy** [comment]
@EricWF, yeah, it seems that if PRs are left unanswered for 6 months they become impossible to merge.  I'll close this and keep using my own fork at pleroy/benchmark.  I am personally not interested in MinGW.

**Comment by mattyclarkson** [comment]
@pleroy, what version of Visual Studio are you using? I can have a look at adding support now that you can get VS for free.

**Comment by pleroy** [comment]
@mattyclarkson: I am using VS 2013.  It's pretty much the only version that makes sense anyway for this code because previous versions didn't have C++11 support.

**Comment by mattyclarkson** [comment]
@pleroy, I'll have a look when I do the MinGW port - hopefully there shouldn't be much that VS needs to get going.

**Comment by mattyclarkson** [comment]
@pleroy, I had a look at getting MSVC up and running on the project. There's not much that needs to be done with regards to polyfilling the unix functions. Only `gettimeofday` really needs to be implemented and the correct headers. I've given up as I can't get on with the MSVC compilers implementation of the C++ standard and the warnings that it throws up. I'll have another look when VS 2015 is out and the compiler has moved along a bit. TBH, by then `clang` will be probably be a better alternative anyway.

**Pull request closed without merging**
