### PR TITLE
fix master branch on *BSD

### PR DESCRIPTION
**Pull request by h-2**
Current master is broken on the BSDs. The little patch below extends the macOS exception to the BSDs.

I have signed the CLA. Should I also add myself to AUTHORS/CONTRIBUTORS?

### CODE REVIEW

**Comment by dominichamon** [comment]
If you want. Let me know either way (we're waiting for the travis builds anyway) and i'll either merge as is or merge with your attribution :)

**Comment by dominichamon** [comment]
Thanks! Merging post testing.

**Comment by h-2** [comment]
Ok, I have added it to CONTRIBUTORS, but not to AUTHORS as the change is so minor it probably doesn't even qualify as a copyrightable work.

**Comment by h-2** [comment]
Thanks for the quick response and review! Ci seems to pass.

**Pull request merged**
