### PR TITLE
Verify RegisterProfilerManager doesn't overwrite an existing registration

### PR DESCRIPTION
**Pull request by xdje42**
Tested:
Configure with:
cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DBENCHMARK_DOWNLOAD_DEPENDENCIES=on
Then run:
ctest -R profiler_manager_gtest
Before change test fails (expected), after change test passes (expected)

### CODE REVIEW

**Comment by dmah42** [comment]
i don't see the test in the PR

**Comment by xdje42** [comment]
Yeah, I wasn't sure how to write a crash test. Is there an existing example?

**Comment by dmah42** [comment]
it would be a standard googletest death test (https://github.com/google/googletest/blob/main/docs/advanced.md#death-tests) .. the test file must end with _gtest.cc so we run it against googletest correctly.  but bear in mind we only assert-fatal in debug, not release.

**Comment by dmah42** [comment]
did you manage to figure out the death test?

**Comment by xdje42** [comment]
Oops. I was away during August, and this got dropped to the bottom of my queue.
Death test added.

**Review by dmah42 — APPROVED** [review]

**Pull request merged**
