### PR TITLE
Introduce test reporter with some reuse of code

### LINKED ISSUE #232: abstract  reporter_output_test.cc
it should be reused between tests.

### PR DESCRIPTION
**Pull request by dominichamon**
Fixes #232

### CODE REVIEW

**Comment by dominichamon** [comment]
@EricWF please take a look

**Comment by dominichamon** [comment]
the travis failure is the clang/gcc 4.6 issue. @EricWF you're best placed to know what if anything we can do about that.

**Comment by EricWF** [comment]
I'll take a look at this tomorrow.

**Comment by EricWF** [comment]
Closing this since another approach has already been committed.

**Pull request closed without merging**
