### PR TITLE
Fix Bazel build breakage caused by commit 6a894bd.

### PR DESCRIPTION
**Pull request by junyer**

### CODE REVIEW

**Comment by junyer** [comment]
Ping, @dominichamon. :)

**Review by dominichamon — APPROVED** [review]

**Comment by dominichamon** [comment]
still confused about why the CI didn't catch this until after i merged. every action is running on push and pull_request.

**Comment by junyer** [comment]
https://github.com/google/benchmark/pull/1373/checks shows that only the CLA check ran that time. O_o

**Comment by dominichamon** [comment]
that's on me then. i should have seen it.

thanks for the quick fix!

**Pull request merged**
