### PR TITLE
Add option to get the verbosity provided by commandline flag -v (#1330)

### PR DESCRIPTION
**Pull request by Matthdonau**

### CODE REVIEW

**Comment by Matthdonau** [comment]
Last push should fix the clang format issue.

**Comment by dominichamon** [comment]
just made one tweak to make sure the test is configured correctly in all cases (replace assert with explicit test failure)

**Comment by Matthdonau** [comment]
@dominichamon this pattern you replaced is also present in spec_arg_test.cc. Maybe you want or want not to change it there as well if asserting is a problem. Just wanted to let you know.

**Comment by dominichamon** [comment]
thanks. i'll take a look at that. i must have missed it.

**Pull request merged**
