### PR TITLE
Fixes #357: broken RMS values when time unit is set.

### LINKED ISSUE #357: RMS calculation seems broken, takes time Unit into account?
Hi.
Consider the [`BM_Complexity_O_N`](https://github.com/google/benchmark/blob/36a251ab3ee4e6dc668129e0ef5fa62b1b8d5d49/test/complexity_test.cc#L80-L113)
Vanilla version outputs:
```
Benchmark                       Time           CPU Iterations
-------------------------------------------------------------
BM_Complexity_O_N/1024        441 ns        441 ns    1583329
BM_Complexity_O_N/2k          881 ns        881 ns     797104
BM_Complexity_O_N/4k         1767 ns       1767 ns     395988
BM_Complexity_O_N/8k         3691 ns       3690 ns     189567
BM_Complexity_O_N/16k        7377 ns       7376 ns      95031
BM_Complexity_O_N/32k       14813 ns      14801 ns      47507
BM_Complexity_O_N/64k       29605 ns      29602 ns      23608
BM_Complexity_O_N_BigO       0.45 N       0.45 N
BM_Complexity_O_N_RMS           0 %          0 %
BM_Complexity_O_N/1024        446 ns        446 ns    1587672
BM_Complexity_O_N/2k          884 ns        884 ns     792614
BM_Complexity_O_N/4k         1787 ns       1786 ns     393225
BM_Complexity_O_N/8k         3684 ns       3683 ns     189791
BM_Complexity_O_N/16k        7373 ns       7369 ns      95181
BM_Complexity_O_N/32k       14716 ns      14711 ns      47732
BM_Complexity_O_N/64k       29714 ns      29707 ns      23656
BM_Complexity_O_N_BigO       0.45 f(N)       0.45 f(N)
BM_Complexity_O_N_RMS           1 %          1 %
BM_Complexity_O_N/1024        442 ns        442 ns    1589204
BM_Complexity_O_N/2k          885 ns        884 ns     788984
BM_Complexity_O_N/4k         1781 ns       1781 ns     390535
BM_Complexity_O_N/8k         3691 ns       3688 ns     189901
BM_Complexity_O_N/16k        7360 ns       7360 ns      93646
BM_Complexity_O_N/32k       14770 ns      14769 ns      47687
BM_Complexity_O_N/64k       29631 ns      29629 ns      23604
BM_Complexity_O_N_BigO       0.45 N       0.45 N
BM_Complexity_O_N_RMS           0 %          0 %
```

However, if i add `->Unit(benchmark::kMillisecond)`, the reported RMS vastly differs:
```
BM_Complexity_O_N/1024          0 ms          0 ms    1591575
BM_Complexity_O_N/2k            0 ms          0 ms     795587
BM_Complexity_O_N/4k            0 ms          0 ms     393170
BM_Complexity_O_N/8k            0 ms          0 ms     189040
BM_Complexity_O_N/16k           0 ms          0 ms      94959
BM_Complexity_O_N/32k           0 ms          0 ms      47290
BM_Complexity_O_N/64k           0 ms          0 ms      23468
BM_Complexity_O_N_BigO       0.45 N       0.45 N
BM_Complexity_O_N_RMS      566108 %     592409 %
BM_Complexity_O_N/1024          0 ms          0 ms    1589498
BM_Complexity_O_N/2k            0 ms          0 ms     795597
BM_Complexity_O_N/4k            0 ms          0 ms     374641
BM_Complexity_O_N/8k            0 ms          0 ms     190103
BM_Complexity_O_N/16k           0 ms          0 ms      95420
BM_Complexity_O_N/32k           0 ms          0 ms      47683
BM_Complexity_O_N/64k           0 ms          0 ms      23639
BM_Complexity_O_N_BigO       0.45 f(N)       0.45 f(N)
BM_Complexity_O_N_RMS      522334 %     490283 %
BM_Complexity_O_N/1024          0 ms          0 ms    1591394
BM_Complexity_O_N/2k            0 ms          0 ms     793333
BM_Complexity_O_N/4k            0 ms          0 ms     391177
BM_Complexity_O_N/8k            0 ms          0 ms     190256
BM_Complexity_O_N/16k           0 ms          0 ms      94733
BM_Complexity_O_N/32k           0 ms          0 ms      47789
BM_Complexity_O_N/64k           0 ms          0 ms      23575
BM_Complexity_O_N_BigO       0.45 N       0.45 N
BM_Complexity_O_N_RMS      492172 %     492850 %
```

The same is valid for all the output formats.
Since BigO is calculated correctly in all cases, i'd think that RMS should be comparable too...

I do agree that in this case, using time units is not as useful. I stumbled onto this when experimenting with benchmarking a case, where 'ms' is the correct time unit.

### PR DESCRIPTION
**Pull request by biojppm**

### CODE REVIEW

**Comment by LebedevRI** [comment]
I think this should also contain the unittest, so that it does not resurface.

**Comment by dominichamon** [comment]
LG but please do add something to a test.

**Comment by biojppm** [comment]
@LebedevRI @dominichamon If the test is to be done right, it's a bit complicated as RMS is an indirect result: its value is not set directly anywhere. I have to think and explore the code about how to fake RMS to a known value (maybe using custom time? ideas are welcome here) so that it can be verified with respect to the time unit. This will take me some time, and I can't do this now as my plate is full. If the correct unit test is really required, just leave this PR hanging and I'll revisit in a couple of weeks. For now @LebedevRI you have the fix (but please confirm).

**Comment by dominichamon** [comment]
i'll take the fix. if you can follow up with a test, that would be great, but we can wait.

**Pull request merged**
